//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 02:48:21 PM CAT 
//


package za.co.nednet.it.contracts.services.ent.productandservicedevelopment.channelproductcatalogue.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetProductHierarchyResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProductHierarchyResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}resultSet" minOccurs="0"/>
 *         &lt;element ref="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}productCatalogue" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProductHierarchyResponseType", propOrder = {
    "resultSet",
    "productCatalogue"
})
public class GetProductHierarchyResponseType {

    protected ResultSetType resultSet;
    protected ProductCatalogueType productCatalogue;

    /**
     * Gets the value of the resultSet property.
     * 
     * @return
     *     possible object is
     *     {@link ResultSetType }
     *     
     */
    public ResultSetType getResultSet() {
        return resultSet;
    }

    /**
     * Sets the value of the resultSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultSetType }
     *     
     */
    public void setResultSet(ResultSetType value) {
        this.resultSet = value;
    }

    /**
     * Gets the value of the productCatalogue property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCatalogueType }
     *     
     */
    public ProductCatalogueType getProductCatalogue() {
        return productCatalogue;
    }

    /**
     * Sets the value of the productCatalogue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCatalogueType }
     *     
     */
    public void setProductCatalogue(ProductCatalogueType value) {
        this.productCatalogue = value;
    }

}
