//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 02:48:21 PM CAT 
//


package za.co.nednet.it.contracts.services.ent.productandservicedevelopment.channelproductcatalogue.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the za.co.nednet.it.contracts.services.ent.productandservicedevelopment.channelproductcatalogue.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProductCatalogueID_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "productCatalogueID");
    private final static QName _RetrieveProducts_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "RetrieveProducts");
    private final static QName _GetProductResponse_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "GetProductResponse");
    private final static QName _ProductCategoryID_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "productCategoryID");
    private final static QName _Product_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "product");
    private final static QName _RetrieveProductsResponse_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "RetrieveProductsResponse");
    private final static QName _ResultSet_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "resultSet");
    private final static QName _ProductIdentifier_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "productIdentifier");
    private final static QName _GetProductHierarchyResponse_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "GetProductHierarchyResponse");
    private final static QName _ProductLinesID_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "productLinesID");
    private final static QName _GetProduct_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "GetProduct");
    private final static QName _GetProductHierarchy_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "GetProductHierarchy");
    private final static QName _ProductFamilyID_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "productFamilyID");
    private final static QName _ProductCatalogue_QNAME = new QName("http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", "productCatalogue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: za.co.nednet.it.contracts.services.ent.productandservicedevelopment.channelproductcatalogue.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link GetProductHierarchyType }
     * 
     */
    public GetProductHierarchyType createGetProductHierarchyType() {
        return new GetProductHierarchyType();
    }

    /**
     * Create an instance of {@link ResultSetType }
     * 
     */
    public ResultSetType createResultSetType() {
        return new ResultSetType();
    }

    /**
     * Create an instance of {@link ProductCatalogueType }
     * 
     */
    public ProductCatalogueType createProductCatalogueType() {
        return new ProductCatalogueType();
    }

    /**
     * Create an instance of {@link RetrieveProductsResponseType }
     * 
     */
    public RetrieveProductsResponseType createRetrieveProductsResponseType() {
        return new RetrieveProductsResponseType();
    }

    /**
     * Create an instance of {@link GetProductHierarchyResponseType }
     * 
     */
    public GetProductHierarchyResponseType createGetProductHierarchyResponseType() {
        return new GetProductHierarchyResponseType();
    }

    /**
     * Create an instance of {@link RetrieveProductsType }
     * 
     */
    public RetrieveProductsType createRetrieveProductsType() {
        return new RetrieveProductsType();
    }

    /**
     * Create an instance of {@link GetProductResponseType }
     * 
     */
    public GetProductResponseType createGetProductResponseType() {
        return new GetProductResponseType();
    }

    /**
     * Create an instance of {@link GetProductType }
     * 
     */
    public GetProductType createGetProductType() {
        return new GetProductType();
    }

    /**
     * Create an instance of {@link FeatureGroupingType }
     * 
     */
    public FeatureGroupingType createFeatureGroupingType() {
        return new FeatureGroupingType();
    }

    /**
     * Create an instance of {@link FilterItemsType }
     * 
     */
    public FilterItemsType createFilterItemsType() {
        return new FilterItemsType();
    }

    /**
     * Create an instance of {@link ProductAttributeGroupType }
     * 
     */
    public ProductAttributeGroupType createProductAttributeGroupType() {
        return new ProductAttributeGroupType();
    }

    /**
     * Create an instance of {@link AttributesType }
     * 
     */
    public AttributesType createAttributesType() {
        return new AttributesType();
    }

    /**
     * Create an instance of {@link ProductPricingType }
     * 
     */
    public ProductPricingType createProductPricingType() {
        return new ProductPricingType();
    }

    /**
     * Create an instance of {@link FeeType }
     * 
     */
    public FeeType createFeeType() {
        return new FeeType();
    }

    /**
     * Create an instance of {@link ProductLinesType }
     * 
     */
    public ProductLinesType createProductLinesType() {
        return new ProductLinesType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link FeaturesType }
     * 
     */
    public FeaturesType createFeaturesType() {
        return new FeaturesType();
    }

    /**
     * Create an instance of {@link FeatureFulfilmentType }
     * 
     */
    public FeatureFulfilmentType createFeatureFulfilmentType() {
        return new FeatureFulfilmentType();
    }

    /**
     * Create an instance of {@link ProductCategoriesType }
     * 
     */
    public ProductCategoriesType createProductCategoriesType() {
        return new ProductCategoriesType();
    }

    /**
     * Create an instance of {@link FeatureAttributeGroupType }
     * 
     */
    public FeatureAttributeGroupType createFeatureAttributeGroupType() {
        return new FeatureAttributeGroupType();
    }

    /**
     * Create an instance of {@link FilterGroupsType }
     * 
     */
    public FilterGroupsType createFilterGroupsType() {
        return new FilterGroupsType();
    }

    /**
     * Create an instance of {@link ProductFamiliesType }
     * 
     */
    public ProductFamiliesType createProductFamiliesType() {
        return new ProductFamiliesType();
    }

    /**
     * Create an instance of {@link ProductattributesType }
     * 
     */
    public ProductattributesType createProductattributesType() {
        return new ProductattributesType();
    }

    /**
     * Create an instance of {@link BasePriceType }
     * 
     */
    public BasePriceType createBasePriceType() {
        return new BasePriceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "productCatalogueID")
    public JAXBElement<String> createProductCatalogueID(String value) {
        return new JAXBElement<String>(_ProductCatalogueID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveProductsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "RetrieveProducts")
    public JAXBElement<RetrieveProductsType> createRetrieveProducts(RetrieveProductsType value) {
        return new JAXBElement<RetrieveProductsType>(_RetrieveProducts_QNAME, RetrieveProductsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "GetProductResponse")
    public JAXBElement<GetProductResponseType> createGetProductResponse(GetProductResponseType value) {
        return new JAXBElement<GetProductResponseType>(_GetProductResponse_QNAME, GetProductResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "productCategoryID")
    public JAXBElement<String> createProductCategoryID(String value) {
        return new JAXBElement<String>(_ProductCategoryID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "product")
    public JAXBElement<ProductType> createProduct(ProductType value) {
        return new JAXBElement<ProductType>(_Product_QNAME, ProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveProductsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "RetrieveProductsResponse")
    public JAXBElement<RetrieveProductsResponseType> createRetrieveProductsResponse(RetrieveProductsResponseType value) {
        return new JAXBElement<RetrieveProductsResponseType>(_RetrieveProductsResponse_QNAME, RetrieveProductsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "resultSet")
    public JAXBElement<ResultSetType> createResultSet(ResultSetType value) {
        return new JAXBElement<ResultSetType>(_ResultSet_QNAME, ResultSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "productIdentifier")
    public JAXBElement<Integer> createProductIdentifier(Integer value) {
        return new JAXBElement<Integer>(_ProductIdentifier_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductHierarchyResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "GetProductHierarchyResponse")
    public JAXBElement<GetProductHierarchyResponseType> createGetProductHierarchyResponse(GetProductHierarchyResponseType value) {
        return new JAXBElement<GetProductHierarchyResponseType>(_GetProductHierarchyResponse_QNAME, GetProductHierarchyResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "productLinesID")
    public JAXBElement<String> createProductLinesID(String value) {
        return new JAXBElement<String>(_ProductLinesID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "GetProduct")
    public JAXBElement<GetProductType> createGetProduct(GetProductType value) {
        return new JAXBElement<GetProductType>(_GetProduct_QNAME, GetProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductHierarchyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "GetProductHierarchy")
    public JAXBElement<GetProductHierarchyType> createGetProductHierarchy(GetProductHierarchyType value) {
        return new JAXBElement<GetProductHierarchyType>(_GetProductHierarchy_QNAME, GetProductHierarchyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "productFamilyID")
    public JAXBElement<String> createProductFamilyID(String value) {
        return new JAXBElement<String>(_ProductFamilyID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductCatalogueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", name = "productCatalogue")
    public JAXBElement<ProductCatalogueType> createProductCatalogue(ProductCatalogueType value) {
        return new JAXBElement<ProductCatalogueType>(_ProductCatalogue_QNAME, ProductCatalogueType.class, null, value);
    }

}
