//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 02:48:21 PM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package za.co.nednet.it.contracts.services.ent.productandservicedevelopment.channelproductcatalogue.v1;
