trigger:
 branches:
   include:
     - release/*

resources:
  repositories:
    - repository: templates
      type: git
      name: Eclipse-1.0/templates
      ref: devops-test

extends:
   template: cfo-repo-build-with-ears.yml@templates