trigger:
 branches:
   include:
     - release/*

resources:
  repositories:
    - repository: templates
      type: git
      name: Eclipse-1.0/templates
      refs: refs/heads/sandbox/nexuscloudtest

extends:
   template: cfo-repo-build-with-ears.yml@templates