//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 02:48:21 PM CAT 
//


package za.co.nednet.it.contracts.services.ent.productandservicedevelopment.channelproductcatalogue.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for FeaturesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeaturesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="featureIdentifier" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="preSelected" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shortDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="featureGrouping" type="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}FeatureGroupingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="featureType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referenceProductID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="featurePricing" type="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}ProductPricingType" minOccurs="0"/>
 *         &lt;element name="featureFulfilment" type="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}FeatureFulfilmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="featureDisplayAdditionalInformationWidget" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="featureOnAPageWebURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="featureDisplayPosition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="featureAttributeGroup" type="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}FeatureAttributeGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeaturesType", propOrder = {
    "featureIdentifier",
    "name",
    "mandatory",
    "preSelected",
    "shortDescription",
    "description",
    "featureGrouping",
    "featureType",
    "referenceProductID",
    "featurePricing",
    "featureFulfilment",
    "featureDisplayAdditionalInformationWidget",
    "featureOnAPageWebURL",
    "featureDisplayPosition",
    "featureAttributeGroup",
    "action",
    "inheritFromFiles"
})
public class FeaturesType implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5839741800555773655L;
	protected Integer featureIdentifier;
    protected String name;
    protected String mandatory;
    protected String preSelected;
    protected String shortDescription;
    protected String description;
    protected List<FeatureGroupingType> featureGrouping;
    protected String featureType;
    protected String referenceProductID;
    protected ProductPricingType featurePricing;
    protected List<FeatureFulfilmentType> featureFulfilment;
    protected String featureDisplayAdditionalInformationWidget;
    protected String featureOnAPageWebURL;
    protected String featureDisplayPosition;
    protected List<FeatureAttributeGroupType> featureAttributeGroup;
    @XmlAttribute
    protected String action;
    @XmlAttribute
    protected String inheritFromFiles;

    /**
     * Gets the value of the featureIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFeatureIdentifier() {
        return featureIdentifier;
    }

    /**
     * Sets the value of the featureIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFeatureIdentifier(Integer value) {
        this.featureIdentifier = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMandatory(String value) {
        this.mandatory = value;
    }

    /**
     * Gets the value of the preSelected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreSelected() {
        return preSelected;
    }

    /**
     * Sets the value of the preSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreSelected(String value) {
        this.preSelected = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the featureGrouping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureGrouping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureGrouping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureGroupingType }
     * 
     * 
     */
    public List<FeatureGroupingType> getFeatureGrouping() {
        if (featureGrouping == null) {
            featureGrouping = new ArrayList<FeatureGroupingType>();
        }
        return this.featureGrouping;
    }

    /**
     * Gets the value of the featureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureType() {
        return featureType;
    }

    /**
     * Sets the value of the featureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureType(String value) {
        this.featureType = value;
    }

    /**
     * Gets the value of the referenceProductID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceProductID() {
        return referenceProductID;
    }

    /**
     * Sets the value of the referenceProductID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceProductID(String value) {
        this.referenceProductID = value;
    }

    /**
     * Gets the value of the featurePricing property.
     * 
     * @return
     *     possible object is
     *     {@link ProductPricingType }
     *     
     */
    public ProductPricingType getFeaturePricing() {
        return featurePricing;
    }

    /**
     * Sets the value of the featurePricing property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductPricingType }
     *     
     */
    public void setFeaturePricing(ProductPricingType value) {
        this.featurePricing = value;
    }

    /**
     * Gets the value of the featureFulfilment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureFulfilment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureFulfilment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureFulfilmentType }
     * 
     * 
     */
    public List<FeatureFulfilmentType> getFeatureFulfilment() {
        if (featureFulfilment == null) {
            featureFulfilment = new ArrayList<FeatureFulfilmentType>();
        }
        return this.featureFulfilment;
    }

    /**
     * Gets the value of the featureDisplayAdditionalInformationWidget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureDisplayAdditionalInformationWidget() {
        return featureDisplayAdditionalInformationWidget;
    }

    /**
     * Sets the value of the featureDisplayAdditionalInformationWidget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureDisplayAdditionalInformationWidget(String value) {
        this.featureDisplayAdditionalInformationWidget = value;
    }

    /**
     * Gets the value of the featureOnAPageWebURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureOnAPageWebURL() {
        return featureOnAPageWebURL;
    }

    /**
     * Sets the value of the featureOnAPageWebURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureOnAPageWebURL(String value) {
        this.featureOnAPageWebURL = value;
    }

    /**
     * Gets the value of the featureDisplayPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureDisplayPosition() {
        return featureDisplayPosition;
    }

    /**
     * Sets the value of the featureDisplayPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureDisplayPosition(String value) {
        this.featureDisplayPosition = value;
    }

    /**
     * Gets the value of the featureAttributeGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureAttributeGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureAttributeGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureAttributeGroupType }
     * 
     * 
     */
    public List<FeatureAttributeGroupType> getFeatureAttributeGroup() {
        if (featureAttributeGroup == null) {
            featureAttributeGroup = new ArrayList<FeatureAttributeGroupType>();
        }
        return this.featureAttributeGroup;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getInheritFromFiles() {
        return inheritFromFiles;
    }

    public void setInheritFromFiles(String inheritFromFiles) {
        this.inheritFromFiles = inheritFromFiles;
    }
}
