//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 02:48:21 PM CAT 
//


package za.co.nednet.it.contracts.services.ent.productandservicedevelopment.channelproductcatalogue.v1;

import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}productIdentifier" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shortDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="productPricing" type="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}ProductPricingType" minOccurs="0"/>
 *         &lt;element name="salesHighlights" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="productOnAPageWebURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productAttributeGroup" type="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}productAttributeGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="features" type="{http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1}FeaturesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductType", propOrder = {
    "productIdentifier",
    "name",
    "shortDescription",
    "description",
    "productPricing",
    "salesHighlights",
    "productOnAPageWebURL",
    "productAttributeGroup",
    "features",
    "inheritFromFiles"
})
@XmlRootElement(name="product")
public class ProductType implements Serializable {

	private static final long serialVersionUID = 3310644094523159806L;
	
	protected Integer productIdentifier;
    protected String name;
    protected String shortDescription;
    protected Object description;
    protected ProductPricingType productPricing;
    protected List<String> salesHighlights;
    protected String productOnAPageWebURL;
    protected List<ProductAttributeGroupType> productAttributeGroup;
    protected List<FeaturesType> features;
    @XmlAttribute
    protected String inheritFromFiles;

    /**
     * Gets the value of the productIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProductIdentifier() {
        return productIdentifier;
    }

    /**
     * Sets the value of the productIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProductIdentifier(Integer value) {
        this.productIdentifier = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDescription(Object value) {
        this.description = value;
    }

    /**
     * Gets the value of the productPricing property.
     * 
     * @return
     *     possible object is
     *     {@link ProductPricingType }
     *     
     */
    public ProductPricingType getProductPricing() {
        return productPricing;
    }

    /**
     * Sets the value of the productPricing property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductPricingType }
     *     
     */
    public void setProductPricing(ProductPricingType value) {
        this.productPricing = value;
    }

    /**
     * Gets the value of the salesHighlights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salesHighlights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesHighlights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSalesHighlights() {
        if (salesHighlights == null) {
            salesHighlights = new ArrayList<String>();
        }
        return this.salesHighlights;
    }

    /**
     * Gets the value of the productOnAPageWebURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductOnAPageWebURL() {
        return productOnAPageWebURL;
    }

    /**
     * Sets the value of the productOnAPageWebURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductOnAPageWebURL(String value) {
        this.productOnAPageWebURL = value;
    }

    /**
     * Gets the value of the productAttributeGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productAttributeGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductAttributeGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductAttributeGroupType }
     * 
     * 
     */
    public List<ProductAttributeGroupType> getProductAttributeGroup() {
        if (productAttributeGroup == null) {
            productAttributeGroup = new ArrayList<ProductAttributeGroupType>();
        }
        return this.productAttributeGroup;
    }

    /**
     * Gets the value of the features property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the features property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeaturesType }
     * 
     * 
     */
    public List<FeaturesType> getFeatures() {
        if (features == null) {
            features = new ArrayList<FeaturesType>();
        }
        return this.features;
    }
    
    public void setFeatures(List<FeaturesType> features) {
    	this.features = features;
    }

    public String getInheritFromFiles() {
        return inheritFromFiles;
    }

    public void setInheritFromFiles(String inheritFromFiles) {
        this.inheritFromFiles = inheritFromFiles;
    }

    @Override
    public String toString() {
        return "ProductType{" +
                "productIdentifier=" + productIdentifier +
                ", name='" + name + '\'' +
                '}';
    }
}
