<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
	xmlns:s2="http://contracts.it.nednet.co.za/Infrastructure/2008/09/EnterpriseContext"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://contracts.it.nednet.co.za/Infrastructure/2008/09/EnterpriseContext">
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://contracts.it.nednet.co.za/Infrastructure/2008/09/EnterpriseContext">
			<xsd:include schemaLocation="EnterpriseContext_2008-09.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="EnterpriseContextHeader">
		<wsdl:part element="s2:EnterpriseContext" name="enterpriseHeader" />
	</wsdl:message>
</wsdl:definitions>
