//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://contracts.it.nednet.co.za/services/ent/productandservicedevelopment/ChannelProductCatalogue/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package za.co.nednet.it.contracts.services.ent.productandservicedevelopment.channelproductcatalogue.v1;
