//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package za.co.nednet.it.contracts.services.ent.productandservicedevelopment.channelproductcatalogue.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductMappingDetailsResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductMappingDetailsResp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="enterpriseProductId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mappedProductId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductMappingDetailsResp", propOrder = {
    "enterpriseProductId",
    "mappedProductId"
})
public class ProductMappingDetailsResp {

    @XmlElement(required = true)
    protected String enterpriseProductId;
    @XmlElement(required = true)
    protected String mappedProductId;

    /**
     * Gets the value of the enterpriseProductId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseProductId() {
        return enterpriseProductId;
    }

    /**
     * Sets the value of the enterpriseProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseProductId(String value) {
        this.enterpriseProductId = value;
    }

    /**
     * Gets the value of the mappedProductId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappedProductId() {
        return mappedProductId;
    }

    /**
     * Sets the value of the mappedProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappedProductId(String value) {
        this.mappedProductId = value;
    }

}
