//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package za.co.nb.productcatalogue.dao.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "debugDatabaseContentsResponse", namespace = "http://dao.productcatalogue.nb.co.za/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "debugDatabaseContentsResponse", namespace = "http://dao.productcatalogue.nb.co.za/")
public class DebugDatabaseContentsResponse {


}
